[package]
name = "flightvars"
version = "0.1.0"
authors = ["Alvaro Polo <apoloval@gmail.com>"]

[dependencies]
byteorder = "0.5"
fsuipc = "0.3"
hex = "0.1"
libc = "*"
log = "0.3"
log4rs = "0.3"
rustc-serialize = "0.3"
tempdir = "0.3.5"
toml = "0.1"

[lib]
crate-type = ["dylib"]
